### ISSUE TITLE
能不能将公共资源导出m3u文件？

### ISSUE THREAD

**Issue by ndcc5** [zhimin-dev/iptv-checker#17]
能不能将公共资源导出m3u文件？

**Comment by zmisgod** [comment]
可以的，需要先【检查直播源是否有效】，检查完毕后,点击【获取有效链接】或者【获取无效链接】，或者手动点击最左侧的checkbox，选择完毕后，点击【导出选中的链接】即可。
------
现在必须要先点击【检查直播源是否有效】按钮，其实这个没必要。我找个时间优化下，再不点击【检查直播源是否有效】勾选了最左侧的checkbox，也可以显示导出按钮。

**Comment by qiulin6** [comment]
能不能直接导入本地的播放列表文件m3u？

**Comment by zmisgod** [comment]
> 能不能直接导入本地的播放列表文件m3u？

好的，后面将支持

**Comment by zmisgod** [comment]
已支持
