### ISSUE TITLE
希望能做一个docker版，为Emby等媒体中心提供直播列表

### ISSUE THREAD

**Issue by EliteOtaku** [zhimin-dev/iptv-checker#29]
本人常用的是Emby，如果把这个app做成docker，部署在nas，定时更新直播列表，这样就可以省去在Emby手动更新的步骤了。

开发者大大的作品很不错，点赞！

**Comment by zmisgod** [comment]
好的，后面将支持，敬请期待

**Comment by naoki66** [comment]
感谢，希望docker版本支持直接编辑频道连接和EPG地址、回访地址等待

**Comment by zmisgod** [comment]
已经支持docker版本了，试试吧！

**Comment by EliteOtaku** [comment]
> 已经支持docker版本了，试试吧！

呃，本人不太会用命令行，本来想在群晖nas上部署，但这个确实搞不懂……能否提供一个docker hub上面的？类似这样的
https://registry.hub.docker.com/r/allanpk716/chinesesubfinder/
我至少会用图形界面一步步安装，再次感谢开发组大大！

**Comment by zmisgod** [comment]
> > 已经支持docker版本了，试试吧！
> 
> 呃，本人不太会用命令行，本来想在群晖nas上部署，但这个确实搞不懂……能否提供一个docker hub上面的？类似这样的 https://registry.hub.docker.com/r/allanpk716/chinesesubfinder/ 我至少会用图形界面一步步安装，再次感谢开发组大大！

好的，我找个时间搞下

**Comment by naoki66** [comment]
> 已经支持docker版本了，试试吧！

非常感谢！还提个小建议，docker能否增加个zmisgod/iptvchecker:latest 标签而不是指定某个版本，以后可以随您仓库的内容更新而更新。

**Comment by zmisgod** [comment]
> > 已经支持docker版本了，试试吧！
> 
> 非常感谢！还提个小建议，docker能否增加个zmisgod/iptvchecker:latest 标签而不是指定某个版本，以后可以随您仓库的内容更新而更新。

可以了，再试试吧
