### ISSUE TITLE
希望检查是否有效的功能添加分辨率和结果导出excel功能

### ISSUE THREAD

**Issue by kof8855** [zhimin-dev/iptv-checker#37]
希望检查是否有效的功能添加分辨率和结果导出excel功能，如果能有下载速度更好

**Comment by zmisgod** [comment]
2.14.0 版本支持导出excel（导出的是csv格式），至于分辨率的功能会考虑在后续支持

**Comment by zmisgod** [comment]
> 希望检查是否有效的功能添加分辨率和结果导出excel功能，如果能有下载速度更好

v2.15 版本已支持分辨率
