### ISSUE TITLE
希望源检测可以后台、并发

### ISSUE THREAD

**Issue by Takamiyasakari** [zhimin-dev/iptv-checker#44]
背景：
当前网页窗口打开，检测当源数量过多，电脑息屏或者一些其他操作网页自动刷新，之前的检测还没结束，结果就没了，又要重新检测，导致一直没法检测完

建议：
1.检测可以改成并发、并发线程可选，默认线程为1或者2
2.检测任务改成创建任务队列形式，即时关闭网页，后台也能继续检测

**Comment by Su-yj** [comment]
我试过了，使用docker部署，重启容器后，上次的任务依然在那里跑，估计网页刷新不会对后台的任务有影响，但是可能就是拿不到结果。
并发检查这个我觉得能加上会更好，毕竟单个检查确实很慢。
另外不知道是否有文档能给出后端调用的接口？方便第三方应用使用。
还有的就是任务跑完后是否有日志文件或任务ID之类的，方便第三方应用调用，或者前端页面因刷新后无法再次拿到结果的问题？

**Comment by zmisgod** [comment]
新版本已经支持后台检查，赶紧试试吧！
