### ISSUE TITLE
2.15.1版本中ipv6无法正常访问

### ISSUE THREAD

**Issue by LucterGee** [zhimin-dev/iptv-checker#49]
2.15.0版本v6是正常的，好像是axios的解析v6地址时候[]的问题

const respData = await instance.request(request)

axois相关issue
[[](url)](https://github.com/axios/axios/issues/5333)

**Comment by zmisgod** [comment]
docker版本已经更新，你拉下最新的docker版本试试，看看问题有没有解决，我本地不支持ipv6，问题复线不了。

**Comment by zmisgod** [comment]
> 2.15.0版本v6是正常的，好像是axios的解析v6地址时候[]的问题
> 
> const respData = await instance.request(request)
> 
> axois相关issue []([axios/axios#5333](https://github.com/axios/axios/issues/5333))

试试最新的cmd命令行检查下，是否支持ipv6

**Comment by zmisgod** [comment]
更新最新的docker版本或者release版本，在系统信息中如果提示【不支持ipv6】那就说明你的网络不支持，否则是支持的
