### ISSUE TITLE
能否支持txt格式文件check？

### ISSUE THREAD

**Issue by ErDongChen1973** [zhimin-dev/iptv-checker#54]

**Comment by zmisgod** [comment]
txt文件里的内容发给我看看

**Comment by zmisgod** [comment]
现在支持类似下面格式的
cctv-1,https://xxxx.cctv.com/11xxxxx.m3u
cctv-2,https://xxxx.cctv.com/22xxxxx.m3u

**Comment by ErDongChen1973** [comment]
你好，这是txt的格式，和m3u差不多，希望能支持，谢谢！


央视频道,#genre#
CCTV-1 综合,http://iptvrr.sh.chinamobile.com:6060/cms001/ch00000090990000001022/index.m3u8
CCTV-2 财经,http://iptvrr.sh.chinamobile.com:6060/cms001/ch00000090990000001220/index.m3u8
CCTV-3 综艺,http://iptvrr.sh.chinamobile.com:6060/cms001/ch00000090990000001186/index.m3u8
CCTV-4 中文国际,http://iptvrr.sh.chinamobile.com:6060/cms001/ch00000090990000001221/index.m3u8
CCTV-5 体育,http://iptvrr.sh.chinamobile.com:6060/cms001/ch00000090990000001187/index.m3u8
CCTV-6 电影,http://iptvrr.sh.chinamobile.com:6060/cms001/ch00000090990000001188/index.m3u8
CCTV-7 国防军事,http://iptvrr.sh.chinamobile.com:6060/cms001/ch00000090990000001236/index.m3u8
CCTV-8 电视剧,http://iptvrr.sh.chinamobile.com:6060/cms001/ch00000090990000001189/index.m3u8
CCTV-9 纪录,http://iptvrr.sh.chinamobile.com:6060/cms001/ch00000090990000001237/index.m3u8
CCTV-10 科教,http://iptvrr.sh.chinamobile.com:6060/cms001/ch00000090990000001238/index.m3u8
CCTV-11 戏曲,http://iptvrr.sh.chinamobile.com:6060/cms001/ch00000090990000001309/index.m3u8
CCTV-12 社会与法,http://iptvrr.sh.chinamobile.com:6060/cms001/ch00000090990000001239/index.m3u8
CCTV-13 新闻,http://iptvrr.sh.chinamobile.com:6060/cms001/ch00000090990000001328/index.m3u8
CCTV-14 少儿,http://iptvrr.sh.chinamobile.com:6060/cms001/ch00000090990000001240/index.m3u8
CCTV-15 音乐,http://iptvrr.sh.chinamobile.com:6060/cms001/ch00000090990000001338/index.m3u8
CCTV-16 奥林匹克,http://iptvrr.sh.chinamobile.com:6060/cms001/ch00000090990000001248/index.m3u8
CCTV-17 农业农村,http://iptvrr.sh.chinamobile.com:6060/cms001/ch00000090990000001241/index.m3u8
CCTV-16 奥林匹克 4K,http://iptvrr.sh.chinamobile.com:6060/cms001/ch00000090990000001258/index.m3u8
CGTN英语,http://iptvrr.sh.chinamobile.com:6060/cms001/ch00000090990000001058/index.m3u8


卫视频道,#genre#
北京卫视,http://iptvrr.sh.chinamobile.com:6060/cms001/ch00000090990000001029/index.m3u8
湖南卫视,http://iptvrr.sh.chinamobile.com:6060/cms001/ch00000090990000001026/index.m3u8
东方卫视,http://iptvrr.sh.chinamobile.com:6060/cms001/ch00000090990000001013/index.m3u8
四川卫视,http://iptvrr.sh.chinamobile.com:6060/cms001/ch00000090990000001130/index.m3u8
天津卫视,http://iptvrr.sh.chinamobile.com:6060/cms001/ch00000090990000001036/index.m3u8







尔苳尘
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhimin-dev/iptv-checker"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月20日(星期六) 上午10:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhimin-dev/iptv-checker] 能否支持txt格式文件check？ (Issue #54)





 
txt文件里的内容发给我看看

**Comment by zmisgod** [comment]
这个是支持的，你可以试试

**Comment by ErDongChen1973** [comment]
> 这个是支持的，你可以试试
![image](https://github.com/zhimin-dev/iptv-checker/assets/44294575/28be240d-a59c-4b25-8171-a354f60ce450)
似乎是解析不了，麻烦修复一下呢

**Comment by ErDongChen1973** [comment]
> 这个是支持的，你可以试试
txt格式的前面多了一个分类
![image](https://github.com/zhimin-dev/iptv-checker/assets/44294575/78d56533-0d0c-471b-a460-e72d6596396a)

**Comment by zmisgod** [comment]
你看下我的最新视频，就是用你的这个案例做的

**Comment by ErDongChen1973** [comment]
> 你看下我的最新视频，就是用你的这个案例做的

哈哈哈，我之前看到你的视频了，提供的链接都挂了（尬住了） 按道理说不应该有问题，我看你用的mac版，后面我再试试
