### ISSUE TITLE
大佬，为什么一直报错？

### ISSUE THREAD

**Issue by hp967** [zhimin-dev/iptv-checker#60]
文件中源总数： 804
检查进度: 380/804thread '<unnamed>' panicked at src/common/check.rs:178:54:
called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Body, source: TimedOut }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
检查进度: 802/804thread '<unnamed>' panicked at src/common/check.rs:178:54:
called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Body, source: TimedOut }

**Comment by zmisgod** [comment]
是请求源超时导致的，可以不用管

**Comment by zmisgod** [comment]
新版已经修复，建议更新新版本
