### ISSUE TITLE
Set up a new port for Docker

### ISSUE THREAD

**Issue by mikal** [zhimin-dev/iptv-checker#61]
Hi Zhimin,
ipvt-checker is a great tool. For docker, may I have a chance to set up a new port in Docker Compose? The port is 8089 by default but it's used by another OS service. Thank you

请教下，因为要测试ipv6的直播源，我使用docker以host部署它，默认使用的8089端口已经被另外一个系统服务占用，请问有没有办法通过环境变量或其他方式，更改这个端口为其他的，比如8098？谢谢！

**Comment by zmisgod** [comment]
docker下个版本我会增加这个这个参数，你可以自定义端口号
