### ISSUE TITLE
新功能建议

### ISSUE THREAD

**Issue by newrookie001** [zhimin-dev/iptv-checker#62]
首先感谢大佬的作品。
其次，有几个产品功能的想法，或许已经在更新的路上。
1、定时任务功能，希望能够添加“筛选频道关键词”，因为采集源内的频道很多，但大家往往仅需要定时更新里面特定频道的数据源，因此希望能够设定关键词，对源数据进行筛选后定时更新。
2、还是定时任务，假如有多个在线链接，源1、源2、源3，里面都有CCTV1，当定时任务执行上述规则筛选的时候，找到了CCTV1，此时，能否对CCTV1的三个源进行合并。（当然这里可能也有难度，毕竟有些源里面命名为“CCTV1”，有些命名为“CCTV1综合”，未必能有效合并）。
3、定时任务的执行结果，目前是可以获得m3u的ip地址；后期能否增加一个功能，可选择将m3u文件，通过本地映射的方式存储到指定的文件目录内。
4、是否有机会，上线一个网络搜索源的功能。

**Comment by zmisgod** [comment]
感谢您的反馈以及建议。
1. 筛选的功能新版本（3.2.0）已经支持，docker版本敬请期待。
2. 这个可以有，后面更新我加下这个功能。
3. docker版本可以把结果目录映射到本地目录的，新版本更新的时候我来讲解一下。
4. 暂无计划。
