### ISSUE TITLE
报错 r.split is not a function

### ISSUE THREAD

**Issue by Suuperfishy** [zhimin-dev/iptv-checker#66]
![e9d9186a86ec6705e3db53b8744de472](https://github.com/zhimin-dev/iptv-checker/assets/79971778/94eb8e33-c14d-41df-958c-67479896d26e)

**Comment by Suuperfishy** [comment]
win11 23H2

**Comment by zmisgod** [comment]
4.0.1 版本修复了，用新版本试试吧
