### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by zxw12315** [zhimin-dev/iptv-checker#67]
系统win10，下载之后，解压，双击运行出现黑窗闪退，原因未知。

**Comment by zmisgod** [comment]
新版本打开还报错吗？

**Comment by zxw12315** [comment]
没有了，正常使用。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年11月08日 04:26 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [zhimin-dev/iptv-checker] 闪退 (Issue #67) |

新版本打开还报错吗？

**Comment by zmisgod** [comment]
好的，那我就先把这个issue关闭了，如果有新的请新开issue，感谢反馈
