### ISSUE TITLE
定时检查任务中不需要检查选项无法生效

### ISSUE THREAD

**Issue by Iensuredit** [zhimin-dev/iptv-checker#77]
### 平台及版本
- Docker，lastest

### 问题描述
- 定时检查任务中将`是否不需要检查`设置为`是`并保存后，该选项无法生效

### 相关截图
![1](https://github.com/user-attachments/assets/ac1e393a-991a-4d23-bfbb-a9f25eb0911f)
![2](https://github.com/user-attachments/assets/ae6884f5-e51a-4c01-9a44-98dcd32fd04f)

**Comment by zmisgod** [comment]
4.1版本会修复，敬请期待
