### ISSUE TITLE
作者你好，能否为您的iptv-checker以及iptv-checker-rs分配许可证

### ISSUE THREAD

**Issue by GrandDuke1106** [zhimin-dev/iptv-checker#80]
如题，希望可以各自分配一个许可证，这样我就可以创造衍生以及使用您的作品了，毕竟一般情况下不分配许可证是不能使用，复制，分发您的作品的。

> 您没有义务选择许可证。但是，如果没有许可证，则默认版权法适用，这意味着您保留对源代码的所有权利，并且任何人都不得复制、分发或创建您的作品的衍生作品。如果您正在创建开源项目，我们强烈建议您包含开源许可证。

[选择正确的许可证](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#choosing-the-right-license)

感谢你写出了如此优秀的软件，感激不尽

**Comment by GrandDuke1106** [comment]
我给iptv-checker-rs写了一个pkgbuild，已上传[aur仓库](https://aur.archlinux.org/packages/iptv-checker-rs-git)，如果有使用arch linux的可以试用一下，欢迎提建议

**Comment by zmisgod** [comment]
好的，我找个时间处理下许可证

**Comment by zmisgod** [comment]
已增加许可证
