### ISSUE TITLE
开发者，你好，最新版本有问题，可以运行，但是打开网页端会提示没有目录，错误 os2

### ISSUE THREAD

**Issue by PQ0000** [zhimin-dev/iptv-checker#84]
最新版本有问题，可以运行，但是打开网页端会提示没有目录，错误 os2
services:
  iptvchecker:
    container_name: myIp
    image: zmisgod/iptvchecker:latest   #（目前用回v4.0.1.1）
    network_mode: host
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

不使用host模式也是一样的，现在已经退回上一个版本了。

**Comment by PQ0000** [comment]
看容器启动日志没有看到报错

**Comment by leishoulin** [comment]
同报该错误

**Comment by zmisgod** [comment]
用最新的版本试试呢？

**Comment by PQ0000** [comment]
> 用最新的版本试试呢？

可以了，非常感谢
