### ISSUE TITLE
欢迎大家提出建议或者意见

### ISSUE THREAD

**Issue by zmisgod** [zhimin-dev/iptv-checker#9]
欢迎大家提出建议或者意见，我们将及时给出反馈。

您的建议可以让本项目走的更远！❤️

**Comment by LongLiveY96** [comment]
这个扩展能否做为项目部署在服务器上呢

**Comment by zmisgod** [comment]
> 这个扩展能否做为项目部署在服务器上呢

不能，这个是客户端，不能部署在服务器上哦！

**Comment by gobiking** [comment]
发布到chrome吧  能自动更新

**Comment by zmisgod** [comment]
> 发布到chrome吧 能自动更新

我也想发布到chrome商店，但是上chrome需要支付5美元，我没有visa卡，验证不了，很尴尬。。。

**Comment by zmisgod** [comment]
> 可以尝试下Edge上传，应该是不需要Visa的

好的，我试试

**Comment by winking324** [comment]
安卓电视盒子上的浏览器，能加载插件么？

**Comment by winking324** [comment]
安卓电视盒子上的浏览器，能加载插件么？

**Comment by zmisgod** [comment]
> 安卓电视盒子上的浏览器，能加载插件么？

貌似不可以，只有电脑端的浏览器才可以

**Comment by calkchu** [comment]
在我有M3U订阅源链接和我有M3U订阅源内容中相继输入很多订阅地址，都显示“未成功解析到数据，请检查输入”，在公共订阅源中选择 china 后，显示“Request failed with status code 404”

**Comment by zmisgod** [comment]
> 在我有M3U订阅源链接和我有M3U订阅源内容中相继输入很多订阅地址，都显示“未成功解析到数据，请检查输入”，在公共订阅源中选择 china 后，显示“Request failed with status code 404”

因为扩展中【公共订阅源】的数据来自：https://github.com/iptv-org/iptv 项目，但是这个项目被封了，所以导致404。可以去github找下其他的项目源

**Comment by calkchu** [comment]
> 

好吧，哎，好好的资源，就没有了，可惜了

**Comment by zmisgod** [comment]
> 好吧，哎，好好的资源，就没有了，可惜了

我觉得这个项目应该可以恢复，耐心等等。

我再找找有哪些靠谱的公共源，如果你这边有，可以一起分享下，哈哈哈

**Comment by calkchu** [comment]
> 

那个项目是不是更改了地址了，是不是把https://github.com/iptv-org/iptv 改成了 https://github.com/iptv-org/database 这个地址，这个你用的到吗？

**Comment by zmisgod** [comment]
> > 
> 
> 那个项目是不是更改了地址了，是不是把https://github.com/iptv-org/iptv 改成了 https://github.com/iptv-org/database 这个地址，这个你用的到吗？

不是这个，2个项目不一样哦！再等等吧。。。

插件我最近可以优化下：如果这个项目[iptv](https://github.com/iptv-org/iptv)恢复了，再开放公共订阅源的tab

**Comment by zmisgod** [comment]
> 源

老铁，https://github.com/iptv-org/iptv  这个项目恢复了，赶紧试试吧，等等党的胜利

**Comment by zmisgod** [comment]
> > 
> 
> 那个项目是不是更改了地址了，是不是把https://github.com/iptv-org/iptv 改成了 https://github.com/iptv-org/database 这个地址，这个你用的到吗？

老铁，https://github.com/iptv-org/iptv 这个项目恢复了，赶紧试试吧，等等党的胜利

**Comment by SmartYou1995** [comment]
可以加入台标整理功能吗？

**Comment by zmisgod** [comment]
如果有建议或者意见请单独提issue
